HW-02
alyonazakharova/js-101-2020 pull request #3
Opened 2021-03-20 21:14 UTC by alyonazakharova

Cypress test for deleteing a todo

2021-04-04 11:24 UTC, DmitryMakhnev requested changes

2021-04-04 11:24 UTC, DmitryMakhnev commented on 09-ts-todo-mvc-react-with-tests/tests/e2e/todos-page/manage-todos.spec.ts
> +      cy.get('[data-test-id=task-counter]').should('have.text', "0 items left");
Нужно так же сделать intercepter на запрос удаления, иначе сейчас у вас проверился только клиентский код, и если он перестанет отправлять на сервер запрос, программа будет работать некорректно, а тест останется зелёным

2021-04-05 12:12 UTC, alyonazakharova commented on 09-ts-todo-mvc-react-with-tests/tests/e2e/todos-page/manage-todos.spec.ts
> +      cy.get('[data-test-id=task-counter]').should('have.text', "0 items left");
Добавила intercept для удаления.
И ещё сделала фикстуру c непустым списком, чтобы в тесте на удаление не проверять то, что проверяется в тесте на создание

2021-04-11 16:46 UTC, DmitryMakhnev approved these changes
Отлично!

2021-04-12 08:10 UTC, closed without merging